// Aurora Song - Department Bonus Dispensation Machine UI Code-Behind

using Content.Client.UserInterface.Controls;
using Content.Shared._AS.Bank;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._AS.Bank.UI;

[GenerateTypedNameReferences]
public sealed partial class DepartmentBonusDispensationMachine : FancyWindow
{
    [Dependency] private readonly IGameTiming _timing = default!;

    public event Action? OnEjectPressed;

    private DepartmentBonusDispensationMachineBoundUserInterfaceState? _currentState;

    public DepartmentBonusDispensationMachine()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        EjectButton.OnPressed += _ => OnEjectPressed?.Invoke();
    }

    public void UpdateState(DepartmentBonusDispensationMachineBoundUserInterfaceState state)
    {
        _currentState = state;

        DepartmentLabel.Text = Loc.GetString("department-bonus-machine-department", ("dept", state.DepartmentName));
        RateLabel.Text = $"{state.TaxRate * 100:F1}%";
        StoredLabel.Text = $"{state.StoredAmount} / {state.MaxStoredAmount}";

        UpdateTimer();

        // Disable eject button if empty
        EjectButton.Disabled = state.StoredAmount <= 0;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_currentState != null)
            UpdateTimer();
    }

    private void UpdateTimer()
    {
        if (_currentState == null)
            return;

        // Calculate time until next payout
        var timeUntil = _currentState.NextWithdrawal - _timing.CurTime;
        if (timeUntil < TimeSpan.Zero)
            timeUntil = TimeSpan.Zero;

        var minutes = (int)timeUntil.TotalMinutes;
        var seconds = timeUntil.Seconds;
        NextPayoutLabel.Text = $"{minutes}:{seconds:D2}";
    }
}
