using Content.Client.Resources;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._NF.LateJoin.ListItems;

[GenerateTypedNameReferences]
public sealed partial class StationListItem : PanelContainer
{
    public sealed class ViewState(
        NetEntity stationEntity,
        string stationName,
        string stationSubtext,
        string stationDescription,
        bool selected,
        string? iconPath)
    {
        public string StationName { get; } = stationName;
        public string StationSubtext { get; } = stationSubtext;
        public string StationDescription { get; } = stationDescription;
        public NetEntity StationEntity { get; } = stationEntity;

        public bool Selected { get; set; } = selected;

        public string IconPath { get; } = iconPath ?? "";
    }

    public StationListItem(ViewState state)
    {
        RobustXamlLoader.Load(this);

        StationName.Text = state.StationName;
        StationSubtext.Text = state.StationSubtext;

        // Disallow repeated selection of same station that does UI reloads.
        StationButton.Disabled = state.Selected;

        if (state.IconPath.Length > 0)
        {
            // Check if this is an RSI path (contains .rsi/)
            // Aurora Song: Support RSI state paths in iconPath by resolving SpriteSystem on demand.
            if (state.IconPath.Contains(".rsi/"))
            {
                var parts = state.IconPath.Split(".rsi/");
                if (parts.Length == 2)
                {
                    var rsiPath = parts[0] + ".rsi";
                    var stateName = parts[1];

                    try
                    {
                        // Aurora Song: Get SpriteSystem via IEntitySystemManager inside a UI control.
                        var entSysMan = IoCManager.Resolve<IEntitySystemManager>();
                        var spriteSystem = entSysMan.GetEntitySystem<SpriteSystem>();
                        StationIcon.Texture = spriteSystem.Frame0(new SpriteSpecifier.Rsi(new ResPath(rsiPath), stateName));
                    }
                    catch
                    {
                        // Fallback to default if RSI loading fails
                    }
                }
            }
            else
            {
                // Regular texture path
                StationIcon.TexturePath = state.IconPath;
            }
        }
    }
}
